// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel::Queryable;

#[derive(Queryable, Debug)]
pub struct Node {
    pub id: Option<i32>,
    pub url: String,
    pub ping: i32,
    pub uptime: i32,
    pub last_checked: i32,
    pub zmq: Option<i32>,
    pub cors: Option<i32>,
}
