
[default]
extend-ignore-identifiers-re = ["8Bhws7zfT7nWhMNCZzBNj7UEJzY1Sw24LMxE629fUnvGgk8DDtwS6S33HPJDFNu6YX1H3azxuCDWbHU8uz8XbwzkSkey6V4", "4AGJScWSv45E28pmwck9YRP21KuwGx6fuMYV9kTxXFnWEij5FVEUyccBs7ExDy419DJXRPw3u57TH5BaGbsHTdnf6SvY5p5"]
